// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: rpcTemplate.proto

package rpcTemplate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDetailListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *UserDetailListRequest) Reset() {
	*x = UserDetailListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailListRequest) ProtoMessage() {}

func (x *UserDetailListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailListRequest.ProtoReflect.Descriptor instead.
func (*UserDetailListRequest) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{0}
}

func (x *UserDetailListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserDetailListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserDetailListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*UserDetailItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *UserDetailListResponse) Reset() {
	*x = UserDetailListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailListResponse) ProtoMessage() {}

func (x *UserDetailListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailListResponse.ProtoReflect.Descriptor instead.
func (*UserDetailListResponse) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetailListResponse) GetItems() []*UserDetailItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UserDetailItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *UserDetailItem) Reset() {
	*x = UserDetailItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailItem) ProtoMessage() {}

func (x *UserDetailItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailItem.ProtoReflect.Descriptor instead.
func (*UserDetailItem) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{2}
}

func (x *UserDetailItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDetailItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserDetailItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserDetailItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type UserDetailUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *UserDetailUpdateQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Doc   *UserDetailUpdateDoc   `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
}

func (x *UserDetailUpdateRequest) Reset() {
	*x = UserDetailUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailUpdateRequest) ProtoMessage() {}

func (x *UserDetailUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserDetailUpdateRequest) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{3}
}

func (x *UserDetailUpdateRequest) GetQuery() *UserDetailUpdateQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *UserDetailUpdateRequest) GetDoc() *UserDetailUpdateDoc {
	if x != nil {
		return x.Doc
	}
	return nil
}

type UserDetailUpdateQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserDetailUpdateQuery) Reset() {
	*x = UserDetailUpdateQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailUpdateQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailUpdateQuery) ProtoMessage() {}

func (x *UserDetailUpdateQuery) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailUpdateQuery.ProtoReflect.Descriptor instead.
func (*UserDetailUpdateQuery) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{4}
}

func (x *UserDetailUpdateQuery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserDetailUpdateDoc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserDetailUpdateDoc) Reset() {
	*x = UserDetailUpdateDoc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailUpdateDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailUpdateDoc) ProtoMessage() {}

func (x *UserDetailUpdateDoc) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailUpdateDoc.ProtoReflect.Descriptor instead.
func (*UserDetailUpdateDoc) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{5}
}

func (x *UserDetailUpdateDoc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserDetailUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserDetailUpdateResponse) Reset() {
	*x = UserDetailUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailUpdateResponse) ProtoMessage() {}

func (x *UserDetailUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailUpdateResponse.ProtoReflect.Descriptor instead.
func (*UserDetailUpdateResponse) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{6}
}

func (x *UserDetailUpdateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserDetailInsertReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserDetailInsertReq) Reset() {
	*x = UserDetailInsertReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailInsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailInsertReq) ProtoMessage() {}

func (x *UserDetailInsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailInsertReq.ProtoReflect.Descriptor instead.
func (*UserDetailInsertReq) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{7}
}

func (x *UserDetailInsertReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserDetailInsertResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserDetailInsertResp) Reset() {
	*x = UserDetailInsertResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailInsertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailInsertResp) ProtoMessage() {}

func (x *UserDetailInsertResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailInsertResp.ProtoReflect.Descriptor instead.
func (*UserDetailInsertResp) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{8}
}

func (x *UserDetailInsertResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserDetailDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserDetailDeleteReq) Reset() {
	*x = UserDetailDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailDeleteReq) ProtoMessage() {}

func (x *UserDetailDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailDeleteReq.ProtoReflect.Descriptor instead.
func (*UserDetailDeleteReq) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{9}
}

func (x *UserDetailDeleteReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserDetailDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserDetailDeleteResp) Reset() {
	*x = UserDetailDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcTemplate_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetailDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailDeleteResp) ProtoMessage() {}

func (x *UserDetailDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcTemplate_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailDeleteResp.ProtoReflect.Descriptor instead.
func (*UserDetailDeleteResp) Descriptor() ([]byte, []int) {
	return file_rpcTemplate_proto_rawDescGZIP(), []int{10}
}

func (x *UserDetailDeleteResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_rpcTemplate_proto protoreflect.FileDescriptor

var file_rpcTemplate_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x22, 0x47, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x4b, 0x0a, 0x16, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x72, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x17, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x32, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x52,
	0x03, 0x64, 0x6f, 0x63, 0x22, 0x27, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a,
	0x13, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x26, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26,
	0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0x81, 0x03, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0e,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22,
	0x2e, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x72, 0x70,
	0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x20, 0x2e, 0x72,
	0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x21,
	0x2e, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x57, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x72, 0x70, 0x63, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f,
	0x72, 0x70, 0x63, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpcTemplate_proto_rawDescOnce sync.Once
	file_rpcTemplate_proto_rawDescData = file_rpcTemplate_proto_rawDesc
)

func file_rpcTemplate_proto_rawDescGZIP() []byte {
	file_rpcTemplate_proto_rawDescOnce.Do(func() {
		file_rpcTemplate_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcTemplate_proto_rawDescData)
	})
	return file_rpcTemplate_proto_rawDescData
}

var file_rpcTemplate_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpcTemplate_proto_goTypes = []interface{}{
	(*UserDetailListRequest)(nil),    // 0: rpcTemplate.UserDetailListRequest
	(*UserDetailListResponse)(nil),   // 1: rpcTemplate.UserDetailListResponse
	(*UserDetailItem)(nil),           // 2: rpcTemplate.UserDetailItem
	(*UserDetailUpdateRequest)(nil),  // 3: rpcTemplate.UserDetailUpdateRequest
	(*UserDetailUpdateQuery)(nil),    // 4: rpcTemplate.UserDetailUpdateQuery
	(*UserDetailUpdateDoc)(nil),      // 5: rpcTemplate.UserDetailUpdateDoc
	(*UserDetailUpdateResponse)(nil), // 6: rpcTemplate.UserDetailUpdateResponse
	(*UserDetailInsertReq)(nil),      // 7: rpcTemplate.UserDetailInsertReq
	(*UserDetailInsertResp)(nil),     // 8: rpcTemplate.UserDetailInsertResp
	(*UserDetailDeleteReq)(nil),      // 9: rpcTemplate.UserDetailDeleteReq
	(*UserDetailDeleteResp)(nil),     // 10: rpcTemplate.UserDetailDeleteResp
}
var file_rpcTemplate_proto_depIdxs = []int32{
	2,  // 0: rpcTemplate.UserDetailListResponse.items:type_name -> rpcTemplate.UserDetailItem
	4,  // 1: rpcTemplate.UserDetailUpdateRequest.query:type_name -> rpcTemplate.UserDetailUpdateQuery
	5,  // 2: rpcTemplate.UserDetailUpdateRequest.doc:type_name -> rpcTemplate.UserDetailUpdateDoc
	0,  // 3: rpcTemplate.UserDetailService.UserDetailList:input_type -> rpcTemplate.UserDetailListRequest
	3,  // 4: rpcTemplate.UserDetailService.UserDetailUpdate:input_type -> rpcTemplate.UserDetailUpdateRequest
	7,  // 5: rpcTemplate.UserDetailService.UserDetailInsert:input_type -> rpcTemplate.UserDetailInsertReq
	9,  // 6: rpcTemplate.UserDetailService.UserDetailDelete:input_type -> rpcTemplate.UserDetailDeleteReq
	1,  // 7: rpcTemplate.UserDetailService.UserDetailList:output_type -> rpcTemplate.UserDetailListResponse
	6,  // 8: rpcTemplate.UserDetailService.UserDetailUpdate:output_type -> rpcTemplate.UserDetailUpdateResponse
	8,  // 9: rpcTemplate.UserDetailService.UserDetailInsert:output_type -> rpcTemplate.UserDetailInsertResp
	10, // 10: rpcTemplate.UserDetailService.UserDetailDelete:output_type -> rpcTemplate.UserDetailDeleteResp
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpcTemplate_proto_init() }
func file_rpcTemplate_proto_init() {
	if File_rpcTemplate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcTemplate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailUpdateQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailUpdateDoc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailInsertReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailInsertResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcTemplate_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetailDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcTemplate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcTemplate_proto_goTypes,
		DependencyIndexes: file_rpcTemplate_proto_depIdxs,
		MessageInfos:      file_rpcTemplate_proto_msgTypes,
	}.Build()
	File_rpcTemplate_proto = out.File
	file_rpcTemplate_proto_rawDesc = nil
	file_rpcTemplate_proto_goTypes = nil
	file_rpcTemplate_proto_depIdxs = nil
}
