// Code generated by goctl. DO NOT EDIT.
// Source: rpcTemplate.proto

package server

import (
	"context"

	"codeup.aliyun.com/64df1ec7dba61e96ebf612bf/jiandaoshou/rpc-template/internal/logic/testuserservice"
	"codeup.aliyun.com/64df1ec7dba61e96ebf612bf/jiandaoshou/rpc-template/internal/svc"
	"codeup.aliyun.com/64df1ec7dba61e96ebf612bf/jiandaoshou/rpc-template/pb/rpcTemplate"
)

type TestUserServiceServer struct {
	svcCtx *svc.ServiceContext
	rpcTemplate.UnimplementedTestUserServiceServer
}

func NewTestUserServiceServer(svcCtx *svc.ServiceContext) *TestUserServiceServer {
	return &TestUserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TestUserServiceServer) GetUserInfo(ctx context.Context, in *rpcTemplate.GetUserRes) (*rpcTemplate.GetUserResp, error) {
	l := testuserservicelogic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *TestUserServiceServer) AddUser(ctx context.Context, in *rpcTemplate.AddUserRes) (*rpcTemplate.AddUserResp, error) {
	l := testuserservicelogic.NewAddUserLogic(ctx, s.svcCtx)
	return l.AddUser(in)
}

func (s *TestUserServiceServer) GetUserList(ctx context.Context, in *rpcTemplate.GetUserListReq) (*rpcTemplate.GetUserListResp, error) {
	l := testuserservicelogic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}

func (s *TestUserServiceServer) UpdUser(ctx context.Context, in *rpcTemplate.UpdUserReq) (*rpcTemplate.UpdUserResp, error) {
	l := testuserservicelogic.NewUpdUserLogic(ctx, s.svcCtx)
	return l.UpdUser(in)
}

func (s *TestUserServiceServer) DelUser(ctx context.Context, in *rpcTemplate.DelUserReq) (*rpcTemplate.DelUserResp, error) {
	l := testuserservicelogic.NewDelUserLogic(ctx, s.svcCtx)
	return l.DelUser(in)
}
